### ISSUE TITLE
does not respect router.prefix

### ISSUE THREAD

**Issue by kevinludwig** [a-s-o/koa-docs#5]
the koa-joi-router allows you to specify a prefix for a group of routes. But the prefix is not rendered onto the routes in the generated docs.

**Comment by a-s-o** [comment]
Alright, this one was straight forward. Groups no accept an additional property called prefix which will be prefixed to the path when rendering. Hope that works. 

Since this is a pretty low impact change I also published this to npm as v0.9.0 along with the other changes to dependencies and so on.

**Comment by a-s-o** [comment]
Closed in  658b19d
