### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by binomialstew** [a-s-o/koa-docs#6]
When running our app using koa-docs 0.9.0, we are getting an `unexpected token =` error at line 72 of koa-docs/src/components/content.js.

```
function routeInfo (method, path, prefix = '') {
                                         ^
```

This is new in 0.9.0.

**Comment by a-s-o** [comment]
Oops,  sorry about that. ES6 has spoiled me. I am running latest node version so didn't see that. I will update later today. Thanks for pointing it out.

**Comment by a-s-o** [comment]
Fixed; removed the default parameter. Please re-open if there are other issues. I don't want to make a whole compilation/build chain but will if necessary

**Comment by binomialstew** [comment]
This is working well, now. Thank you.
